version: '3.8'

services:
  backend:
    container_name: backend_v2
    image: backend-img:v2
    build: ./backend
    ports:
      - "5100:5100"
    volumes:
      - /home/${USER}/data:/app/data  # Bind mount for data
      - /home/${USER}/logs:/app/logs  # Bind mount for logs
    restart: unless-stopped

  frontend:
    container_name: frontend_v2
    image: frontend-img:v2
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend    # service name, not container name
    environment:
      #- BACKEND_URL=http://backend_v2:5100    # when we want to use Docker DNS
      - ENV=prod
    volumes:
      - /home/${USER}/logs:/app/logs  # Bind mount for logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

