version: '3.8'

services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "5100:5100"
    # Docker Compose removes containers when you stop them, 
    # so there's no direct equivalent to --rm. Use 'docker-compose down' to remove.

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5100
      - ENV=prod
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # No direct 'it' equivalent, as compose services run in detached mode by default.



