version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5100:5100"

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5100
